### PR TITLE
Added instructions to add epub check and folder to path

### PR DESCRIPTION
**Pull request by mrandrewandrade**
Added instructions to add epub check and folder to path to help beginners get the necessary requirements.

### CODE REVIEW

**Comment by mhartl** [comment]
The problem is that this won't necessarily work. On many systems, you'll have to add `$HOME/bin` to the path by editing `.bashrc` or `.bash_profile`.

**Comment by mrandrewandrade** [comment]
This better?

https://github.com/mrandrewandrade/softcover_book/commit/7a881995094b9c31c2b4c4e03e784a9cb9deba82

**Comment by mrandrewandrade** [comment]
If someone has to use google to figure it out, it might discourage them and they might give up. I would have found something like this very helpful

**Comment by mhartl** [comment]
Thanks for the contribution. I added some miscellaneous corrections and polish in [this commit](https://github.com/softcover/softcover_book/commit/64bea8529ae7972e9b722e52f1157f100b4aa41c).

**Pull request merged**
